# Generated by Django 5.2.7 on 2026-01-19 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_articolo_data_articolo_visualizzazioni_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articolo',
            old_name='data',
            new_name='data_articolo',
        ),
    ]
