# Generated by Django 5.2.7 on 2026-01-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_data_articolo_data_articolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='data_articolo',
            field=models.DateField(blank=True),
        ),
    ]
