# Generated by Django 5.2.7 on 2026-02-23 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contatto',
            options={'verbose_name': 'Contatto', 'verbose_name_plural': 'Contatti'},
        ),
    ]
